// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/romangurevitch/go-training/internal/bank/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// CreateAccount provides a mock function for the type Service
func (_mock *Service) CreateAccount(ctx context.Context, owner string) (*domain.Account, error) {
	ret := _mock.Called(ctx, owner)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 *domain.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Account, error)); ok {
		return returnFunc(ctx, owner)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Account); ok {
		r0 = returnFunc(ctx, owner)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, owner)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type Service_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
func (_e *Service_Expecter) CreateAccount(ctx interface{}, owner interface{}) *Service_CreateAccount_Call {
	return &Service_CreateAccount_Call{Call: _e.mock.On("CreateAccount", ctx, owner)}
}

func (_c *Service_CreateAccount_Call) Run(run func(ctx context.Context, owner string)) *Service_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_CreateAccount_Call) Return(account *domain.Account, err error) *Service_CreateAccount_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *Service_CreateAccount_Call) RunAndReturn(run func(ctx context.Context, owner string) (*domain.Account, error)) *Service_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// Deposit provides a mock function for the type Service
func (_mock *Service) Deposit(ctx context.Context, accountID string, amount int64) error {
	ret := _mock.Called(ctx, accountID, amount)

	if len(ret) == 0 {
		panic("no return value specified for Deposit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = returnFunc(ctx, accountID, amount)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_Deposit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deposit'
type Service_Deposit_Call struct {
	*mock.Call
}

// Deposit is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - amount int64
func (_e *Service_Expecter) Deposit(ctx interface{}, accountID interface{}, amount interface{}) *Service_Deposit_Call {
	return &Service_Deposit_Call{Call: _e.mock.On("Deposit", ctx, accountID, amount)}
}

func (_c *Service_Deposit_Call) Run(run func(ctx context.Context, accountID string, amount int64)) *Service_Deposit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Service_Deposit_Call) Return(err error) *Service_Deposit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_Deposit_Call) RunAndReturn(run func(ctx context.Context, accountID string, amount int64) error) *Service_Deposit_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccount provides a mock function for the type Service
func (_mock *Service) GetAccount(ctx context.Context, id string) (*domain.Account, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAccount")
	}

	var r0 *domain.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Account, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Account); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_GetAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccount'
type Service_GetAccount_Call struct {
	*mock.Call
}

// GetAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Service_Expecter) GetAccount(ctx interface{}, id interface{}) *Service_GetAccount_Call {
	return &Service_GetAccount_Call{Call: _e.mock.On("GetAccount", ctx, id)}
}

func (_c *Service_GetAccount_Call) Run(run func(ctx context.Context, id string)) *Service_GetAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_GetAccount_Call) Return(account *domain.Account, err error) *Service_GetAccount_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *Service_GetAccount_Call) RunAndReturn(run func(ctx context.Context, id string) (*domain.Account, error)) *Service_GetAccount_Call {
	_c.Call.Return(run)
	return _c
}

// Transfer provides a mock function for the type Service
func (_mock *Service) Transfer(ctx context.Context, fromID string, toID string, amount int64) error {
	ret := _mock.Called(ctx, fromID, toID, amount)

	if len(ret) == 0 {
		panic("no return value specified for Transfer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64) error); ok {
		r0 = returnFunc(ctx, fromID, toID, amount)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_Transfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transfer'
type Service_Transfer_Call struct {
	*mock.Call
}

// Transfer is a helper method to define mock.On call
//   - ctx context.Context
//   - fromID string
//   - toID string
//   - amount int64
func (_e *Service_Expecter) Transfer(ctx interface{}, fromID interface{}, toID interface{}, amount interface{}) *Service_Transfer_Call {
	return &Service_Transfer_Call{Call: _e.mock.On("Transfer", ctx, fromID, toID, amount)}
}

func (_c *Service_Transfer_Call) Run(run func(ctx context.Context, fromID string, toID string, amount int64)) *Service_Transfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Service_Transfer_Call) Return(err error) *Service_Transfer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_Transfer_Call) RunAndReturn(run func(ctx context.Context, fromID string, toID string, amount int64) error) *Service_Transfer_Call {
	_c.Call.Return(run)
	return _c
}

// Withdraw provides a mock function for the type Service
func (_mock *Service) Withdraw(ctx context.Context, accountID string, amount int64) error {
	ret := _mock.Called(ctx, accountID, amount)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = returnFunc(ctx, accountID, amount)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_Withdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Withdraw'
type Service_Withdraw_Call struct {
	*mock.Call
}

// Withdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - amount int64
func (_e *Service_Expecter) Withdraw(ctx interface{}, accountID interface{}, amount interface{}) *Service_Withdraw_Call {
	return &Service_Withdraw_Call{Call: _e.mock.On("Withdraw", ctx, accountID, amount)}
}

func (_c *Service_Withdraw_Call) Run(run func(ctx context.Context, accountID string, amount int64)) *Service_Withdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Service_Withdraw_Call) Return(err error) *Service_Withdraw_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_Withdraw_Call) RunAndReturn(run func(ctx context.Context, accountID string, amount int64) error) *Service_Withdraw_Call {
	_c.Call.Return(run)
	return _c
}
