// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/romangurevitch/go-training/internal/basics/mocking/calculator (interfaces: Adder)
//
// Generated by this command:
//
//	mockgen -destination=internal/basics/mocking/calculator/mocks/mock_adder.go -package=mocks github.com/romangurevitch/go-training/internal/basics/mocking/calculator Adder
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAdder is a mock of Adder interface.
type MockAdder struct {
	ctrl     *gomock.Controller
	recorder *MockAdderMockRecorder
	isgomock struct{}
}

// MockAdderMockRecorder is the mock recorder for MockAdder.
type MockAdderMockRecorder struct {
	mock *MockAdder
}

// NewMockAdder creates a new mock instance.
func NewMockAdder(ctrl *gomock.Controller) *MockAdder {
	mock := &MockAdder{ctrl: ctrl}
	mock.recorder = &MockAdderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdder) EXPECT() *MockAdderMockRecorder {
	return m.recorder
}

// SingleDigitAdd mocks base method.
func (m *MockAdder) SingleDigitAdd(x, y int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SingleDigitAdd", x, y)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SingleDigitAdd indicates an expected call of SingleDigitAdd.
func (mr *MockAdderMockRecorder) SingleDigitAdd(x, y any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SingleDigitAdd", reflect.TypeOf((*MockAdder)(nil).SingleDigitAdd), x, y)
}
