// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/romangurevitch/go-training/internal/temporal/activities (interfaces: InventoryChecker)
//
// Generated by this command:
//
//	mockgen-v0.6.0 -destination=internal/temporal/activities/mocks/mock_inventory_checker.go -package=mocks github.com/romangurevitch/go-training/internal/temporal/activities InventoryChecker
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockInventoryChecker is a mock of InventoryChecker interface.
type MockInventoryChecker struct {
	ctrl     *gomock.Controller
	recorder *MockInventoryCheckerMockRecorder
	isgomock struct{}
}

// MockInventoryCheckerMockRecorder is the mock recorder for MockInventoryChecker.
type MockInventoryCheckerMockRecorder struct {
	mock *MockInventoryChecker
}

// NewMockInventoryChecker creates a new mock instance.
func NewMockInventoryChecker(ctrl *gomock.Controller) *MockInventoryChecker {
	mock := &MockInventoryChecker{ctrl: ctrl}
	mock.recorder = &MockInventoryCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInventoryChecker) EXPECT() *MockInventoryCheckerMockRecorder {
	return m.recorder
}

// CheckInventory mocks base method.
func (m *MockInventoryChecker) CheckInventory(arg0 context.Context, arg1 uuid.UUID, arg2 int32) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckInventory", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckInventory indicates an expected call of CheckInventory.
func (mr *MockInventoryCheckerMockRecorder) CheckInventory(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckInventory", reflect.TypeOf((*MockInventoryChecker)(nil).CheckInventory), arg0, arg1, arg2)
}
