// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/romangurevitch/go-training/internal/bank/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// GetAccount provides a mock function for the type Repository
func (_mock *Repository) GetAccount(ctx context.Context, id string) (*domain.Account, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAccount")
	}

	var r0 *domain.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Account, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Account); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_GetAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccount'
type Repository_GetAccount_Call struct {
	*mock.Call
}

// GetAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Repository_Expecter) GetAccount(ctx interface{}, id interface{}) *Repository_GetAccount_Call {
	return &Repository_GetAccount_Call{Call: _e.mock.On("GetAccount", ctx, id)}
}

func (_c *Repository_GetAccount_Call) Run(run func(ctx context.Context, id string)) *Repository_GetAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_GetAccount_Call) Return(account *domain.Account, err error) *Repository_GetAccount_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *Repository_GetAccount_Call) RunAndReturn(run func(ctx context.Context, id string) (*domain.Account, error)) *Repository_GetAccount_Call {
	_c.Call.Return(run)
	return _c
}

// ListTransactions provides a mock function for the type Repository
func (_mock *Repository) ListTransactions(ctx context.Context, accountID string) ([]domain.Transaction, error) {
	ret := _mock.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for ListTransactions")
	}

	var r0 []domain.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]domain.Transaction, error)); ok {
		return returnFunc(ctx, accountID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.Transaction); ok {
		r0 = returnFunc(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_ListTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTransactions'
type Repository_ListTransactions_Call struct {
	*mock.Call
}

// ListTransactions is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *Repository_Expecter) ListTransactions(ctx interface{}, accountID interface{}) *Repository_ListTransactions_Call {
	return &Repository_ListTransactions_Call{Call: _e.mock.On("ListTransactions", ctx, accountID)}
}

func (_c *Repository_ListTransactions_Call) Run(run func(ctx context.Context, accountID string)) *Repository_ListTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_ListTransactions_Call) Return(transactions []domain.Transaction, err error) *Repository_ListTransactions_Call {
	_c.Call.Return(transactions, err)
	return _c
}

func (_c *Repository_ListTransactions_Call) RunAndReturn(run func(ctx context.Context, accountID string) ([]domain.Transaction, error)) *Repository_ListTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// SaveAccount provides a mock function for the type Repository
func (_mock *Repository) SaveAccount(ctx context.Context, account *domain.Account) error {
	ret := _mock.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for SaveAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Account) error); ok {
		r0 = returnFunc(ctx, account)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_SaveAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAccount'
type Repository_SaveAccount_Call struct {
	*mock.Call
}

// SaveAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - account *domain.Account
func (_e *Repository_Expecter) SaveAccount(ctx interface{}, account interface{}) *Repository_SaveAccount_Call {
	return &Repository_SaveAccount_Call{Call: _e.mock.On("SaveAccount", ctx, account)}
}

func (_c *Repository_SaveAccount_Call) Run(run func(ctx context.Context, account *domain.Account)) *Repository_SaveAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Account
		if args[1] != nil {
			arg1 = args[1].(*domain.Account)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_SaveAccount_Call) Return(err error) *Repository_SaveAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_SaveAccount_Call) RunAndReturn(run func(ctx context.Context, account *domain.Account) error) *Repository_SaveAccount_Call {
	_c.Call.Return(run)
	return _c
}

// SaveTransaction provides a mock function for the type Repository
func (_mock *Repository) SaveTransaction(ctx context.Context, transaction *domain.Transaction) error {
	ret := _mock.Called(ctx, transaction)

	if len(ret) == 0 {
		panic("no return value specified for SaveTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Transaction) error); ok {
		r0 = returnFunc(ctx, transaction)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_SaveTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveTransaction'
type Repository_SaveTransaction_Call struct {
	*mock.Call
}

// SaveTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - transaction *domain.Transaction
func (_e *Repository_Expecter) SaveTransaction(ctx interface{}, transaction interface{}) *Repository_SaveTransaction_Call {
	return &Repository_SaveTransaction_Call{Call: _e.mock.On("SaveTransaction", ctx, transaction)}
}

func (_c *Repository_SaveTransaction_Call) Run(run func(ctx context.Context, transaction *domain.Transaction)) *Repository_SaveTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Transaction
		if args[1] != nil {
			arg1 = args[1].(*domain.Transaction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_SaveTransaction_Call) Return(err error) *Repository_SaveTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_SaveTransaction_Call) RunAndReturn(run func(ctx context.Context, transaction *domain.Transaction) error) *Repository_SaveTransaction_Call {
	_c.Call.Return(run)
	return _c
}
